### ISSUE TITLE
Ошибка при получении коллекции подписантов

### ISSUE THREAD

**Issue by nfyrjd1** [CryptoPro/phpcades#2]
Здравствуйте, установили расширение на debian 12, php 7.4 по [инструкции](https://docs.cryptopro.ru/cades/phpcades/phpcades-install), добились чтобы проходила проверка подписи, но возникает ошибка при попытке достать коллекцию подписантов ([CadesSignedData ](https://docs.cryptopro.ru/cades/reference/cadescom/cadescom_class/cadessigneddata)/ [Signers](https://learn.microsoft.com/en-us/windows/win32/seccrypto/signeddata-signers)).

Текст ошибки:
`/usr/sbin/apache2: symbol lookup error: /usr/lib/php/20190902/libphpcades.so: undefined symbol: _ZN9CryptoPro3PKI5CAdES24CPPCadesSignedDataObject11get_SignersERN5boost10shared_ptrINS1_18CPPCadesCollectionINS1_22CPPCadesCPSignerObjectEEEEE`

Код:
```
$file = base64_encode(file_get_contents('./report-413.docx'));
$signedFile = 'Строка с подписью файла';
$signedData = new CPSignedData();
$signedData->set_ContentEncoding($CADESCOM_BASE64_TO_BINARY);
$signedData->set_Content($file);
$signedData->VerifyCades($signedFile, $CADESCOM_CADES_BES, 1);
$signers = $signedData->get_Signers();
```

Ошибка падает именно на последней строке. Подскажите в чём может быть проблема?

**Comment by cpsdenis** [comment]
Здравствуйте! Подскажите, какая версия CSP у вас используется?
Если 5.0.13300, попробуйте, пожалуйста, пересобрать с сертифицированной сборкой 5.0.13000.

**Comment by nfyrjd1** [comment]
Спасибо, помогло! Также заработал метод `VerifyHash`, там была похожая ошибка:
`_ZN9CryptoPro3PKI5CAdES24CPPCadesSignedDataObject10VerifyHashERN5boost10shared_ptrINS1_26CPPCadesCPHashedDataObjectEEERKNS_5CBlobE20_CADESCOM_CADES_TYPE`
